#ifndef CONSTRAINTS_H
#define CONSTRAINTS_H

#define WRONG_AMOUNT 1
#define WRONG_FILE 2
#define EMPTY_FILE 3
#define WRONG_AMOUNT_ARGUMENTS 53
#define WRONG_COMPARE_ARGUMENT 53
#define WRONG_LEN 6
#define WRONG_NAME 7
#define WRONG_PRODUCER 8
#define WRONG_PRICE 9
#define WRONG_QUANTITY 10
#define NOT_SORTED 11

#define NAME_LEN 30
#define PRODUCER_LEN 15
#define MAX_PRODUCTS 30

#endif